### ISSUE TITLE
how to use this program

### ISSUE THREAD

**Issue by babbu3682** [CplNathan/Nathans-Tarkov-Radar-Public#2]
could you teach me the Usage?

**Comment by CplNathan** [comment]
Hi,
There are many resources available that teach you how to setup a KVM environment that supports something like this;
https://www.youtube.com/watch?v=SsgI1mkx6iw https://www.reddit.com/r/VFIO/comments/f15cok/how_to_setup_kvm_for_gaming/ https://www.mathiashueber.com/fighting-error-43-nvidia-gpu-virtual-machine/

You will need to update the offsets however if you do end up using this program that can be found in the Unknown Cheats reversal thread.

There should be enough resources to get you going, unfortunately I don't offer any kind of 1-1 tutoring service ^.^

Thanks
