### ISSUE TITLE
Looking Glass was NOT designed for cheating in games

### ISSUE THREAD

**Issue by gnif** [CplNathan/Nathans-Tarkov-Radar-Public#3]
Please pull this code and stop promoting its use as a cheating tool, not only are you going to screw over the gamers that it's used against, you are going to screw over the many users that use this tool for legitimate purposes. If the host program gets flagged by anti-cheat software you are going to kill this project and destroy a movement that is allowing thousands of people to move to run Windows as a secondary OS to Linux. The damage you are doing here is enormous and reaches far beyond the game you are enabling people to cheat in.

**Comment by CplNathan** [comment]
I have taken down the LG Tarkov branch.
I apologize for any inconvenience this may have caused for your project.

**Comment by gnif** [comment]
Thank you kindly.
