### ISSUE TITLE
Hello, could you do the same but on CSGO

### ISSUE THREAD

**Issue by mrranger** [CplNathan/Nathans-Tarkov-Radar-Public#6]
Hello, could you do the same but on CSGO, without dma, just an external cheat

**Comment by CplNathan** [comment]
Hi,
There is no reason this couldn't be applied to another game, the idea is nothing new.
Although the entire project is written around the idea if abstracting its presence using a virtual machine and DMA, you could definitely achieve something similar for far less in CSGO.
